version: '3.9'
services:
  server:
    build:
      context: ./Server
      dockerfile: ./CodeGenRestAPI/Dockerfile
    ports:
      - "5000:5000"

  client:
    build:
      context: ./Client
      dockerfile: ./Dockerfile
    ports:
      - "80:80"